FROM node:22-alpine

WORKDIR /app

COPY /frontend/package.json /app/package.json
COPY /frontend/pnpm-lock.yaml /app/pnpm-lock.yaml

RUN corepack enable && corepack prepare pnpm@latest --activate

RUN pnpm install

COPY /frontend /app

COPY .env /app/.env

ARG VITE_SIGNALLING_SERVER_URL

ENV VITE_SIGNALLING_SERVER_URL=$VITE_SIGNALLING_SERVER_URL

RUN pnpm build

CMD ["pnpm", "preview", "--host"]

EXPOSE 5173