FROM node:22-alpine

WORKDIR /app

COPY /server/package.json ./package.json
COPY /server/pnpm-lock.yaml ./pnpm-lock.yaml

RUN corepack enable && corepack prepare pnpm@latest --activate

RUN pnpm install

RUN pnpm install typescript

COPY /server ./

RUN pnpm build

CMD ["pnpm", "start"]

EXPOSE 3000